[project]
authors = ["Gianluca Della Vedova <gianluca@dellavedova.org>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "foundationsCS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
notebook = ">=7.2.2,<8"
sqlite = ">=3.47.0,<4"
pandas = ">=2.2.3,<3"
jupyterlab = ">=4.2.5,<5"
sqlalchemy = ">=2.0.36,<3"
pyarrow = ">=18.0.0,<19"
fastparquet = ">=2024.5.0,<2025"
