# Pandas

First we have to import the library

In [16]:
import pandas as pd

Read the [ex-data/Northwind/Orders.csv](https://github.com/gdv/foundationsCS/raw/main/students/ex-data/Northwind/Orders.csv) file. Notice that the contents of the file are now in a `DataFrame`

In [17]:
orders = pd.read_csv("https://github.com/gdv/foundationsCS/raw/main/students/ex-data/Northwind/Orders.csv")

In [18]:
orders

Id CustomerId  EmployeeId            OrderDate         RequiredDate  \
0      10248      VINET           5           2012-07-04           2012-08-01   
1      10249      TOMSP           6           2012-07-05           2012-08-16   
2      10250      HANAR           4           2012-07-08           2012-08-05   
3      10251      VICTE           3           2012-07-08           2012-08-05   
4      10252      SUPRD           4           2012-07-09           2012-08-06   
...      ...        ...         ...                  ...                  ...   
16813  27061      FOLKO           5  2013-06-29 21:05:55  2013-08-02 04:10:53   
16814  27062      FRANK           2  2014-01-19 12:27:11  2014-01-24 15:15:31   
16815  27063      ALFKI           5  2014-10-15 09:51:09  2014-11-11 14:31:37   
16816  27064      TRADH           8  2013-02-07 02:06:05  2013-03-14 09:43:16   
16817  27065      ANATR           1  2013-08-31 02:59:28  2013-09-15 23:11:49   

               ShippedDate  ShipVia  Freight                        ShipName  \
0               2012-07-16        3    16.75       Vins et alcools Chevalier   
1               2012-07-10        1    22.25              Toms Spezialitäten   
2               2012-07-12        2    25.00                   Hanari Carnes   
3               2012-07-15        1    20.25            Victuailles en stock   
4               2012-07-11        2    36.25                Suprêmes délices   
...                    ...      ...      ...                             ...   
16813  2013-07-02 16:05:51        3   307.25              Familia Arquibaldo   
16814  2014-01-27 02:14:31        2   550.50                        Bon app'   
16815  2014-10-16 06:26:55        1   328.50  Furia Bacalhau e Frutos do Mar   
16816  2013-02-24 10:15:47        3   357.00                     Wilman Kala   
16817  2013-09-03 14:09:08        3   233.75                LINO-Delicateses   

                   ShipAddress         ShipCity       ShipRegion  \
0           59 rue de l'Abbaye            Reims   Western Europe   
1                Luisenstr. 48          Münster   Western Europe   
2              Rua do Paço, 67   Rio de Janeiro    South America   
3           2, rue du Commerce             Lyon   Western Europe   
4         Boulevard Tirou, 255        Charleroi   Western Europe   
...                        ...              ...              ...   
16813             Rua Orós, 92        Sao Paulo    South America   
16814     12, rue des Bouchers        Marseille   Western Europe   
16815   Jardim das rosas n. 32           Lisboa  Southern Europe   
16816            Keskuskatu 45         Helsinki      Scandinavia   
16817  Ave. 5 de Mayo Porlamar  I. de Margarita    South America   

      ShipPostalCode ShipCountry  
0              51100      France  
1              44087     Germany  
2          05454-876      Brazil  
3              69004      France  
4             B-6000     Belgium  
...              ...         ...  
16813      05442-030      Brazil  
16814          13008      France  
16815           1675    Portugal  
16816          21240     Finland  
16817           4980   Venezuela  

[16818 rows x 14 columns]

## Most common `read_csv` options

*  `sep` or `delimiter`: the string that separates the fields. 
*  `delim_whitespace`: a boolean that states if any whitespace is the delimiter
*  `skiprows`: lines to skip. Usually at the beginning of the file, if it contains a comment
*  `nrows`: number of rows to read. Useful for debugging on huge files
*  `low_memory`: boolean (default `True`). Sometimes messes up parsing
*  `na_values`, `keep_default_na`, `na_filter`: change the default behavior for parsing missing data
*  `parse_dates`: dates are a mess to parse. State which columns contain dates
*  `infer_datetime_format`, `dayfirst`: may speed up parsing dates
*  `thousands`, `decimal`: hints for parsing non US-based numbers
*  `encoding`: sometimes you have to set it to `utf-8`

## Series vs DataFrame

A `Series` has a single column. A `DataFrame` at least two columns and an index.

Extract the column `CustomerId` from `Orders`

In [19]:
orders['CustomerId']

0        VINET
1        TOMSP
2        HANAR
3        VICTE
4        SUPRD
         ...  
16813    FOLKO
16814    FRANK
16815    ALFKI
16816    TRADH
16817    ANATR
Name: CustomerId, Length: 16818, dtype: object

What does it happen if I use the wrong column name?

In [42]:
orders['custormerid']

KeyError: 'custormerid'

In [21]:
type(orders['CustomerId'])

pandas.core.series.Series

In [22]:
type(orders)

pandas.core.frame.DataFrame

Show the first rows of `Orders`

In [23]:
orders.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  
0  Western Europe          51100      France  
1  Western Europe          44087     Germany  
2   South America      05454-876      Brazil  
3  Western Europe          69004      France  
4  Western Europe         B-6000     Belgium

Show the size of `Orders`

In [24]:
orders.shape

(16818, 14)

Show the column names of `Orders`

In [25]:
orders.columns

Index(['Id', 'CustomerId', 'EmployeeId', 'OrderDate', 'RequiredDate',
       'ShippedDate', 'ShipVia', 'Freight', 'ShipName', 'ShipAddress',
       'ShipCity', 'ShipRegion', 'ShipPostalCode', 'ShipCountry'],
      dtype='object')

Change the column name `ShipVia` to `Via`

In [26]:
orders.rename(columns = {'ShipVia': 'Via'})
orders.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  
0  Western Europe          51100      France  
1  Western Europe          44087     Germany  
2   South America      05454-876      Brazil  
3  Western Europe          69004      France  
4  Western Europe         B-6000     Belgium

In [27]:
newdf = orders.rename(columns = {'ShipVia': 'Via'})
newdf.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  Via  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16    3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10    1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12    2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15    1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11    2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  
0  Western Europe          51100      France  
1  Western Europe          44087     Germany  
2   South America      05454-876      Brazil  
3  Western Europe          69004      France  
4  Western Europe         B-6000     Belgium

Build a new column `Freight_kg` obtained by multiplying `Freight` by 1000

In [28]:
orders['Freight_kg'] = 1000 * orders['Freight']
orders.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  Freight_kg  
0  Western Europe          51100      France     16750.0  
1  Western Europe          44087     Germany     22250.0  
2   South America      05454-876      Brazil     25000.0  
3  Western Europe          69004      France     20250.0  
4  Western Europe         B-6000     Belgium     36250.0

Use `Id` as the index

In [29]:
orders.set_index('Id')

CustomerId  EmployeeId            OrderDate         RequiredDate  \
Id                                                                       
10248      VINET           5           2012-07-04           2012-08-01   
10249      TOMSP           6           2012-07-05           2012-08-16   
10250      HANAR           4           2012-07-08           2012-08-05   
10251      VICTE           3           2012-07-08           2012-08-05   
10252      SUPRD           4           2012-07-09           2012-08-06   
...          ...         ...                  ...                  ...   
27061      FOLKO           5  2013-06-29 21:05:55  2013-08-02 04:10:53   
27062      FRANK           2  2014-01-19 12:27:11  2014-01-24 15:15:31   
27063      ALFKI           5  2014-10-15 09:51:09  2014-11-11 14:31:37   
27064      TRADH           8  2013-02-07 02:06:05  2013-03-14 09:43:16   
27065      ANATR           1  2013-08-31 02:59:28  2013-09-15 23:11:49   

               ShippedDate  ShipVia  Freight                        ShipName  \
Id                                                                             
10248           2012-07-16        3    16.75       Vins et alcools Chevalier   
10249           2012-07-10        1    22.25              Toms Spezialitäten   
10250           2012-07-12        2    25.00                   Hanari Carnes   
10251           2012-07-15        1    20.25            Victuailles en stock   
10252           2012-07-11        2    36.25                Suprêmes délices   
...                    ...      ...      ...                             ...   
27061  2013-07-02 16:05:51        3   307.25              Familia Arquibaldo   
27062  2014-01-27 02:14:31        2   550.50                        Bon app'   
27063  2014-10-16 06:26:55        1   328.50  Furia Bacalhau e Frutos do Mar   
27064  2013-02-24 10:15:47        3   357.00                     Wilman Kala   
27065  2013-09-03 14:09:08        3   233.75                LINO-Delicateses   

                   ShipAddress         ShipCity       ShipRegion  \
Id                                                                 
10248       59 rue de l'Abbaye            Reims   Western Europe   
10249            Luisenstr. 48          Münster   Western Europe   
10250          Rua do Paço, 67   Rio de Janeiro    South America   
10251       2, rue du Commerce             Lyon   Western Europe   
10252     Boulevard Tirou, 255        Charleroi   Western Europe   
...                        ...              ...              ...   
27061             Rua Orós, 92        Sao Paulo    South America   
27062     12, rue des Bouchers        Marseille   Western Europe   
27063   Jardim das rosas n. 32           Lisboa  Southern Europe   
27064            Keskuskatu 45         Helsinki      Scandinavia   
27065  Ave. 5 de Mayo Porlamar  I. de Margarita    South America   

      ShipPostalCode ShipCountry  Freight_kg  
Id                                            
10248          51100      France     16750.0  
10249          44087     Germany     22250.0  
10250      05454-876      Brazil     25000.0  
10251          69004      France     20250.0  
10252         B-6000     Belgium     36250.0  
...              ...         ...         ...  
27061      05442-030      Brazil    307250.0  
27062          13008      France    550500.0  
27063           1675    Portugal    328500.0  
27064          21240     Finland    357000.0  
27065           4980   Venezuela    233750.0  

[16818 rows x 14 columns]

In [30]:
orders.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  Freight_kg  
0  Western Europe          51100      France     16750.0  
1  Western Europe          44087     Germany     22250.0  
2   South America      05454-876      Brazil     25000.0  
3  Western Europe          69004      France     20250.0  
4  Western Europe         B-6000     Belgium     36250.0

In [31]:
orders.set_index('Id', inplace = True)
orders.head()

CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
Id                                                                           
10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

       Freight                   ShipName           ShipAddress  \
Id                                                                
10248    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye   
10249    22.25         Toms Spezialitäten         Luisenstr. 48   
10250    25.00              Hanari Carnes       Rua do Paço, 67   
10251    20.25       Victuailles en stock    2, rue du Commerce   
10252    36.25           Suprêmes délices  Boulevard Tirou, 255   

             ShipCity      ShipRegion ShipPostalCode ShipCountry  Freight_kg  
Id                                                                            
10248           Reims  Western Europe          51100      France     16750.0  
10249         Münster  Western Europe          44087     Germany     22250.0  
10250  Rio de Janeiro   South America      05454-876      Brazil     25000.0  
10251            Lyon  Western Europe          69004      France     20250.0  
10252       Charleroi  Western Europe         B-6000     Belgium     36250.0

Restore the old index

In [32]:
orders.reset_index(inplace = True)

In [33]:
orders.head()

Id CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
0  10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
1  10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
2  10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
3  10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
4  10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   

   Freight                   ShipName           ShipAddress        ShipCity  \
0    16.75  Vins et alcools Chevalier    59 rue de l'Abbaye           Reims   
1    22.25         Toms Spezialitäten         Luisenstr. 48         Münster   
2    25.00              Hanari Carnes       Rua do Paço, 67  Rio de Janeiro   
3    20.25       Victuailles en stock    2, rue du Commerce            Lyon   
4    36.25           Suprêmes délices  Boulevard Tirou, 255       Charleroi   

       ShipRegion ShipPostalCode ShipCountry  Freight_kg  
0  Western Europe          51100      France     16750.0  
1  Western Europe          44087     Germany     22250.0  
2   South America      05454-876      Brazil     25000.0  
3  Western Europe          69004      France     20250.0  
4  Western Europe         B-6000     Belgium     36250.0

Extract all rows where `ShipVia` is equal to 2

In [34]:
orders[orders['ShipVia'] == 2]

Id CustomerId  EmployeeId            OrderDate         RequiredDate  \
2      10250      HANAR           4           2012-07-08           2012-08-05   
4      10252      SUPRD           4           2012-07-09           2012-08-06   
5      10253      HANAR           3           2012-07-10           2012-07-24   
6      10254      CHOPS           5           2012-07-11           2012-08-08   
8      10256      WELLI           3           2012-07-15           2012-08-12   
...      ...        ...         ...                  ...                  ...   
16805  27053      GREAL           5  2015-03-11 05:01:22  2015-04-16 11:32:55   
16806  27054      LEHMS           7  2015-07-03 10:33:10  2015-07-28 18:20:58   
16810  27058      SPECD           7  2013-01-26 20:46:03  2013-02-23 17:45:40   
16811  27059      BLAUS           3  2013-10-24 03:03:17  2013-11-13 15:25:08   
16814  27062      FRANK           2  2014-01-19 12:27:11  2014-01-24 15:15:31   

               ShippedDate  ShipVia  Freight                        ShipName  \
2               2012-07-12        2    25.00                   Hanari Carnes   
4               2012-07-11        2    36.25                Suprêmes délices   
5               2012-07-16        2    35.50                   Hanari Carnes   
6               2012-07-23        2    24.25               Chop-suey Chinese   
8               2012-07-17        2    16.75          Wellington Importadora   
...                    ...      ...      ...                             ...   
16805  2015-03-15 13:36:35        2   249.75  Furia Bacalhau e Frutos do Mar   
16806  2015-07-21 14:02:12        2   219.25      Centro comercial Moctezuma   
16810  2013-01-28 14:46:44        2   282.25           Bottom-Dollar Markets   
16811  2013-10-25 01:35:28        2   429.25           Bottom-Dollar Markets   
16814  2014-01-27 02:14:31        2   550.50                        Bon app'   

                   ShipAddress        ShipCity       ShipRegion  \
2              Rua do Paço, 67  Rio de Janeiro    South America   
4         Boulevard Tirou, 255       Charleroi   Western Europe   
5              Rua do Paço, 67  Rio de Janeiro    South America   
6                 Hauptstr. 31            Bern   Western Europe   
8           Rua do Mercado, 12         Resende    South America   
...                        ...             ...              ...   
16805   Jardim das rosas n. 32          Lisboa  Southern Europe   
16806  Sierras de Granada 9993     México D.F.  Central America   
16810       23 Tsawassen Blvd.       Tsawassen    North America   
16811       23 Tsawassen Blvd.       Tsawassen    North America   
16814     12, rue des Bouchers       Marseille   Western Europe   

      ShipPostalCode  ShipCountry  Freight_kg  
2          05454-876       Brazil     25000.0  
4             B-6000      Belgium     36250.0  
5          05454-876       Brazil     35500.0  
6               3012  Switzerland     24250.0  
8          08737-363       Brazil     16750.0  
...              ...          ...         ...  
16805           1675     Portugal    249750.0  
16806          05022       Mexico    219250.0  
16810        T2F 8M4       Canada    282250.0  
16811        T2F 8M4       Canada    429250.0  
16814          13008       France    550500.0  

[5592 rows x 15 columns]

What is `orders['ShipVia'] == 2`?

In [35]:
orders['ShipVia'] == 2

0        False
1        False
2         True
3        False
4         True
         ...  
16813    False
16814     True
16815    False
16816    False
16817    False
Name: ShipVia, Length: 16818, dtype: bool

Extract the `Id` of the rows where `ShipVia` is equal to 2

In [36]:
orders[orders['ShipVia'] == 2]['Id']

2        10250
4        10252
5        10253
6        10254
8        10256
         ...  
16805    27053
16806    27054
16810    27058
16811    27059
16814    27062
Name: Id, Length: 5592, dtype: int64

Extract the `Id` and `CustomerId` of the rows where `ShipVia` is equal to 2

In [37]:
orders[orders['ShipVia'] == 2][['Id', 'CustomerId']]

Id CustomerId
2      10250      HANAR
4      10252      SUPRD
5      10253      HANAR
6      10254      CHOPS
8      10256      WELLI
...      ...        ...
16805  27053      GREAL
16806  27054      LEHMS
16810  27058      SPECD
16811  27059      BLAUS
16814  27062      FRANK

[5592 rows x 2 columns]

Use `Id` as the index

In [38]:
orders.set_index('Id', inplace = True)

In [39]:
orders.head(10)

CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
Id                                                                           
10248      VINET           5  2012-07-04   2012-08-01  2012-07-16        3   
10249      TOMSP           6  2012-07-05   2012-08-16  2012-07-10        1   
10250      HANAR           4  2012-07-08   2012-08-05  2012-07-12        2   
10251      VICTE           3  2012-07-08   2012-08-05  2012-07-15        1   
10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   
10253      HANAR           3  2012-07-10   2012-07-24  2012-07-16        2   
10254      CHOPS           5  2012-07-11   2012-08-08  2012-07-23        2   
10255      RICSU           9  2012-07-12   2012-08-09  2012-07-15        3   
10256      WELLI           3  2012-07-15   2012-08-12  2012-07-17        2   
10257      HILAA           4  2012-07-16   2012-08-13  2012-07-22        3   

       Freight                   ShipName  \
Id                                          
10248    16.75  Vins et alcools Chevalier   
10249    22.25         Toms Spezialitäten   
10250    25.00              Hanari Carnes   
10251    20.25       Victuailles en stock   
10252    36.25           Suprêmes délices   
10253    35.50              Hanari Carnes   
10254    24.25          Chop-suey Chinese   
10255    37.50         Richter Supermarkt   
10256    16.75     Wellington Importadora   
10257    21.50           HILARION-Abastos   

                                      ShipAddress        ShipCity  \
Id                                                                  
10248                          59 rue de l'Abbaye           Reims   
10249                               Luisenstr. 48         Münster   
10250                             Rua do Paço, 67  Rio de Janeiro   
10251                          2, rue du Commerce            Lyon   
10252                        Boulevard Tirou, 255       Charleroi   
10253                             Rua do Paço, 67  Rio de Janeiro   
10254                                Hauptstr. 31            Bern   
10255                                 Starenweg 5          Genève   
10256                          Rua do Mercado, 12         Resende   
10257  Carrera 22 con Ave. Carlos Soublette #8-35   San Cristóbal   

           ShipRegion ShipPostalCode  ShipCountry  Freight_kg  
Id                                                             
10248  Western Europe          51100       France     16750.0  
10249  Western Europe          44087      Germany     22250.0  
10250   South America      05454-876       Brazil     25000.0  
10251  Western Europe          69004       France     20250.0  
10252  Western Europe         B-6000      Belgium     36250.0  
10253   South America      05454-876       Brazil     35500.0  
10254  Western Europe           3012  Switzerland     24250.0  
10255  Western Europe           1204  Switzerland     37500.0  
10256   South America      08737-363       Brazil     16750.0  
10257   South America           5022    Venezuela     21500.0

Extract the fifth and tenth row.

In [40]:
orders.iloc[[4, 9]]

CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
Id                                                                           
10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   
10257      HILAA           4  2012-07-16   2012-08-13  2012-07-22        3   

       Freight          ShipName                                 ShipAddress  \
Id                                                                             
10252    36.25  Suprêmes délices                        Boulevard Tirou, 255   
10257    21.50  HILARION-Abastos  Carrera 22 con Ave. Carlos Soublette #8-35   

            ShipCity      ShipRegion ShipPostalCode ShipCountry  Freight_kg  
Id                                                                           
10252      Charleroi  Western Europe         B-6000     Belgium     36250.0  
10257  San Cristóbal   South America           5022   Venezuela     21500.0

Extract the rows with `Id` equal to 10252, 10257.

In [41]:
orders.loc[[10252, 10257]]

CustomerId  EmployeeId   OrderDate RequiredDate ShippedDate  ShipVia  \
Id                                                                           
10252      SUPRD           4  2012-07-09   2012-08-06  2012-07-11        2   
10257      HILAA           4  2012-07-16   2012-08-13  2012-07-22        3   

       Freight          ShipName                                 ShipAddress  \
Id                                                                             
10252    36.25  Suprêmes délices                        Boulevard Tirou, 255   
10257    21.50  HILARION-Abastos  Carrera 22 con Ave. Carlos Soublette #8-35   

            ShipCity      ShipRegion ShipPostalCode ShipCountry  Freight_kg  
Id                                                                           
10252      Charleroi  Western Europe         B-6000     Belgium     36250.0  
10257  San Cristóbal   South America           5022   Venezuela     21500.0